# Note: Use nektos/act for local testing.
name: "pes__gh-action_container-build"
description: "Build container, tag and push to registry."
author: "Pieter E Smit"
inputs:
  args:
    description: "Optional args"
    required: false
    default: "defaultMsg"
runs:
  using: "composite"
  steps:
    - id: print
      shell: bash
      run: |
        echo "start action diepes/gh-action_container-build"
    - name: Check out code
      uses: actions/checkout@v3
    - name: Generate tags
      id: tags
      shell: bash
      run: |
          echo "SHA=$GITHUB_SHA  $GITHUB_BRANCH"
          git_ref=$( echo "${GITHUB_REF_NAME}" | sed 's/[^a-zA-Z0-9]/_/g')
          git_hash=${GITHUB_SHA:0:12}
          date_now=$(date +'%Y%m%dT%Hh%M')
          container="${{ secrets.ACR_SERVER }}/${{ github.repository }}"
          tag="${date_now}-${git_ref}-${git_hash}"
          echo "container=${container} tag=${tag}"
          # Save variables for next step
          echo "container=${container}" >> $GITHUB_ENV
          echo "tag=${tag}" >> $GITHUB_ENV
          echo "ci_url=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> $GITHUB_ENV    


    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
          image: tm-service
          platform: linux/amd64
          tags: ${{ env.tag }}, latest
          registry: ${{ secrets.ACR_SERVER }}
          dockerfile: Dockerfile-k8s
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_ACCESSTOKEN }}           
branding:
  icon: "compass"
  color: "red"